<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1804" started-at="2020-03-03T08:49:45Z" finished-at="2020-03-03T08:49:47Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="1804" started-at="2020-03-03T08:49:45Z" finished-at="2020-03-03T08:49:47Z">
      <class name="com.jbk.Testcase2">
        <test-method status="PASS" signature="checkTitle()[pri:0, instance:com.jbk.Testcase2@3ffc5af1]" name="checkTitle" duration-ms="11" started-at="2020-03-03T08:49:46Z" finished-at="2020-03-03T08:49:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTitle -->
        <test-method status="FAIL" signature="checkUsersTitle()[pri:0, instance:com.jbk.Testcase2@3ffc5af1]" name="checkUsersTitle" duration-ms="1048" started-at="2020-03-03T08:49:46Z" finished-at="2020-03-03T08:49:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [JavaByKiran | User]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [JavaByKiran | User]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.jbk.Testcase2.checkUsersTitle(Testcase2.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkUsersTitle -->
      </class> <!-- com.jbk.Testcase2 -->
      <class name="com.jbk.Testcase1">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.jbk.Testcase1@29774679]" name="setup" is-config="true" duration-ms="16642" started-at="2020-03-03T08:48:10Z" finished-at="2020-03-03T08:48:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.jbk.Testcase2@3ffc5af1]" name="setup" is-config="true" duration-ms="77913" started-at="2020-03-03T08:48:27Z" finished-at="2020-03-03T08:49:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="checklogIn()[pri:0, instance:com.jbk.Testcase1@29774679]" name="checklogIn" duration-ms="564" started-at="2020-03-03T08:49:45Z" finished-at="2020-03-03T08:49:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [error] but found [Please enter email as kiran@gmail.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [error] but found [Please enter email as kiran@gmail.com]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.jbk.Testcase1.checklogIn(Testcase1.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checklogIn -->
        <test-method status="PASS" signature="checktitle()[pri:0, instance:com.jbk.Testcase1@29774679]" name="checktitle" duration-ms="12" started-at="2020-03-03T08:49:46Z" finished-at="2020-03-03T08:49:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checktitle -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.jbk.Testcase1@29774679]" name="close" is-config="true" duration-ms="407" started-at="2020-03-03T08:49:47Z" finished-at="2020-03-03T08:49:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.jbk.Testcase2@3ffc5af1]" name="close" is-config="true" duration-ms="433" started-at="2020-03-03T08:49:47Z" finished-at="2020-03-03T08:49:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.jbk.Testcase1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
